"""added transaction to capholds

Revision ID: 676bbcceb10d
Revises: d4dda7b8d53e
Create Date: 2023-01-12 22:46:25.411508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676bbcceb10d'
down_revision = 'd4dda7b8d53e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cap_hold', schema=None) as batch_op:
        batch_op.add_column(sa.Column('associated_transaction_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_cap_hold_associated_transaction_id_transactions'), 'transactions', ['associated_transaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cap_hold', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cap_hold_associated_transaction_id_transactions'), type_='foreignkey')
        batch_op.drop_column('associated_transaction_id')

    # ### end Alembic commands ###
