"""added open and close transaction to roster_players

Revision ID: 75ca58db40f2
Revises: 183d46d74f9a
Create Date: 2023-01-12 22:26:14.707234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ca58db40f2'
down_revision = '183d46d74f9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roster_player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open_transaction_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('close_transaction_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_roster_player_close_transaction_id_transactions'), 'transactions', ['close_transaction_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_roster_player_open_transaction_id_transactions'), 'transactions', ['open_transaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roster_player', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_roster_player_open_transaction_id_transactions'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_roster_player_close_transaction_id_transactions'), type_='foreignkey')
        batch_op.drop_column('close_transaction_id')
        batch_op.drop_column('open_transaction_id')

    # ### end Alembic commands ###
