"""initial migration

Revision ID: 84dd16d1212d
Revises: 
Create Date: 2022-11-30 13:57:38.143871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84dd16d1212d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roster', schema=None) as batch_op:
        batch_op.drop_column('player_id')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teamname', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('teamname')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('roster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
