"""changed name of transaction table, added fk to trade_Transaction

Revision ID: b7c7d334460b
Revises: 
Create Date: 2023-01-06 15:45:34.877657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7c7d334460b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    with op.batch_alter_table('trade_transaction', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_trade_transaction_transaction_id_transactions'), 'transactions', ['transaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_transaction', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_trade_transaction_transaction_id_transactions'), type_='foreignkey')

    op.create_table('transaction',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('roster_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dropped_player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('added_player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('added_salary', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('status_updated_dt_ms', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('transaction_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_transaction')
    )
    # ### end Alembic commands ###
