"""added notes to rosterplayer

Revision ID: d4dda7b8d53e
Revises: 75ca58db40f2
Create Date: 2023-01-12 22:36:14.494554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4dda7b8d53e'
down_revision = '75ca58db40f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roster_player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=200), nullable=True))

    with op.batch_alter_table('trade_transaction', schema=None) as batch_op:
        batch_op.drop_column('status_updated_dt_ms')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('status_updated_dt_ms')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_updated_dt_ms', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    with op.batch_alter_table('trade_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_updated_dt_ms', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    with op.batch_alter_table('roster_player', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
