"""added error log field

Revision ID: f34732a2e96c
Revises: 676bbcceb10d
Create Date: 2023-01-13 11:51:43.291504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34732a2e96c'
down_revision = '676bbcceb10d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('error_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roster_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('error_log', schema=None) as batch_op:
        batch_op.drop_column('roster_id')

    # ### end Alembic commands ###
